server:
  port: 8087
spring:
  application:
    name: enrrollment-service
    
  data:
    mongodb:
      host: localhost
      port: 27017
      database: users
      username: diana
      password: mongo
      authentication-database: admin
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
  
